/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hr.algebra.views.moviemanager;

import hr.algebra.dal.Repository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.models.Actor;
import hr.algebra.models.ActorTransferable;
import hr.algebra.models.Director;
import hr.algebra.models.DirectorTransferable;
import hr.algebra.models.Movie;
import hr.algebra.models.MovieActor;
import hr.algebra.models.MovieArchive;
import hr.algebra.models.MovieDirector;
import hr.algebra.models.enums.RepoType;
import hr.algebra.utilities.FileUtils;
import hr.algebra.utilities.IconUtils;
import hr.algebra.utilities.JAXBUtils;
import hr.algebra.utilities.MessageUtils;
import hr.algebra.view.models.MovieTableModel;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.TreeSet;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.ListSelectionModel;
import javax.swing.text.JTextComponent;
import java.util.stream.Collectors;
import javax.swing.DefaultListModel;
import javax.swing.DropMode;
import javax.swing.JComponent;
import javax.swing.TransferHandler;

/**
 *
 * @author Nix
 */
public class Movies extends javax.swing.JPanel {

    private static final String DIR = "assets";
    private static final String FILENAME = "src/main/resources/movies.xml";

    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;

    private Repository<Movie> movieRepo;
    private Repository<Director> directorRepo;
    private Repository<Actor> actorRepo;
    private Repository<MovieDirector> movieDirectorRepo;
    private Repository<MovieActor> movieActorRepo;

    private MovieTableModel movieTableModel;

    private Movie selectedMovie;

    private final DefaultListModel<Director> allDirectorsModel = new DefaultListModel<>();
    private final DefaultListModel<Actor> allActorsModel = new DefaultListModel<>();

    private final DefaultListModel<Director> directorsModel = new DefaultListModel<>();
    private final DefaultListModel<Actor> actorsModel = new DefaultListModel<>();

    private Set<Director> directorsSet = new HashSet<>();
    private Set<Actor> actorsSet = new HashSet<>();

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMovies = new javax.swing.JTable();
        tfTitle = new javax.swing.JTextField();
        lbTitleError = new javax.swing.JLabel();
        tfPubDate = new javax.swing.JTextField();
        lbPubDateError = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbDescriptionError = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        tfOriginalTitle = new javax.swing.JTextField();
        lbOriginalTitleError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        spDuration = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tfYearOfRelease = new javax.swing.JTextField();
        lbYearOfReleaseError = new javax.swing.JLabel();
        tfGenre = new javax.swing.JTextField();
        lbGenreError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbIcon = new javax.swing.JLabel();
        tfPoster = new javax.swing.JTextField();
        btnChoose = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfLink = new javax.swing.JTextField();
        lbLinkError = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfReservation = new javax.swing.JTextField();
        lbReservationError = new javax.swing.JLabel();
        lbTrailer = new javax.swing.JLabel();
        tfTrailer = new javax.swing.JTextField();
        lbTrailerError = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lsDirectors = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lsActors = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lsAllDirectors = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lsAllActors = new javax.swing.JList<>();
        jLabel14 = new javax.swing.JLabel();
        lbPicturePathError = new javax.swing.JLabel();
        btnDirectorRemove = new javax.swing.JButton();
        btnActorRemove = new javax.swing.JButton();
        btnSaveAllMovies = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Title");

        tblMovies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMoviesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMovies);

        lbTitleError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTitleError.setForeground(new java.awt.Color(255, 0, 0));
        lbTitleError.setText("X");

        tfPubDate.setName("PubDate"); // NOI18N

        lbPubDateError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPubDateError.setForeground(new java.awt.Color(255, 0, 0));
        lbPubDateError.setText("X");

        jLabel4.setText("Published date");

        lbDescriptionError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbDescriptionError.setForeground(new java.awt.Color(255, 0, 0));
        lbDescriptionError.setText("X");

        jLabel5.setText("Description");

        taDescription.setColumns(20);
        taDescription.setLineWrap(true);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        lbOriginalTitleError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbOriginalTitleError.setForeground(new java.awt.Color(255, 0, 0));
        lbOriginalTitleError.setText("X");

        jLabel2.setText("Original title");

        jLabel3.setText("Duration");

        spDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 500, 1));

        jLabel6.setText("Year of release");

        tfYearOfRelease.setName("YearOfRelease"); // NOI18N

        lbYearOfReleaseError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbYearOfReleaseError.setForeground(new java.awt.Color(255, 0, 0));
        lbYearOfReleaseError.setText("X");

        lbGenreError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbGenreError.setForeground(new java.awt.Color(255, 0, 0));
        lbGenreError.setText("X");

        jLabel7.setText("Genre");

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no_image.jpeg"))); // NOI18N

        tfPoster.setEditable(false);

        btnChoose.setText("Choose");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        jLabel8.setText("Link");

        lbLinkError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbLinkError.setForeground(new java.awt.Color(255, 0, 0));
        lbLinkError.setText("X");

        jLabel9.setText("Reservation");

        lbReservationError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbReservationError.setForeground(new java.awt.Color(255, 0, 0));
        lbReservationError.setText("X");

        lbTrailer.setText("Trailer");

        lbTrailerError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTrailerError.setForeground(new java.awt.Color(255, 0, 0));
        lbTrailerError.setText("X");

        jScrollPane3.setViewportView(lsDirectors);

        jLabel10.setText("Directors");

        jLabel11.setText("All directors");

        jScrollPane4.setViewportView(lsActors);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel12.setText("Actors");

        jScrollPane5.setViewportView(lsAllDirectors);

        jLabel13.setText("All actors");

        jScrollPane6.setViewportView(lsAllActors);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Movies");

        lbPicturePathError.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbPicturePathError.setForeground(new java.awt.Color(255, 0, 0));
        lbPicturePathError.setText("X");

        btnDirectorRemove.setText("Remove");
        btnDirectorRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorRemoveActionPerformed(evt);
            }
        });

        btnActorRemove.setText("Remove");
        btnActorRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorRemoveActionPerformed(evt);
            }
        });

        btnSaveAllMovies.setText("Save all movies");
        btnSaveAllMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAllMoviesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaveAllMovies, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDescriptionError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfPubDate, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPubDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbGenreError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfYearOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbYearOfReleaseError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfReservation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfLink, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTrailer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTrailer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfOriginalTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbOriginalTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbLinkError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbReservationError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbTrailerError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lbPicturePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(219, 219, 219)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActorRemove)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDirectorRemove))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDirectorRemove)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPicturePathError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPoster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnChoose))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfOriginalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbOriginalTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbLinkError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfReservation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbReservationError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbTrailerError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbDescriptionError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfYearOfRelease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbYearOfReleaseError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbGenreError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActorRemove))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPubDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPubDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addGap(26, 26, 26)
                        .addComponent(btnSaveAllMovies)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void tblMoviesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMoviesMouseClicked
        try {
            showMovie();
        } catch (Exception ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblMoviesMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (!formValid()) {
            return;
        }

        try {
            String localPicturePath = uploadPicture();
            Movie movie = new Movie(
                    tfTitle.getText().trim(),
                    LocalDateTime.parse(tfPubDate.getText().trim(), Movie.DATE_TIME_FORMATTER),
                    taDescription.getText().trim(),
                    tfOriginalTitle.getText().trim(),
                    (int) spDuration.getValue(),
                    Integer.parseInt(tfYearOfRelease.getText().trim()),
                    tfGenre.getText().trim(),
                    localPicturePath,
                    tfLink.getText().trim(),
                    tfReservation.getText().trim(),
                    tfTrailer.getText().trim()
            );

            int movieId = movieRepo.createSingle(movie);

            if (!directorsSet.isEmpty()) {
                addMovieDirectors(movieId);
            }

            if (!actorsSet.isEmpty()) {
                addMovieActors(movieId);
            }

            movieTableModel.setMovies(movieRepo.selectAll());
            clearForm();
        } catch (IOException ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDirectorRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorRemoveActionPerformed
        directorsSet.remove(lsDirectors.getSelectedValue());
        loadDirectorsModel();
    }//GEN-LAST:event_btnDirectorRemoveActionPerformed

    private void btnActorRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActorRemoveActionPerformed
        actorsSet.remove(lsActors.getSelectedValue());
        loadActorsModel();
    }//GEN-LAST:event_btnActorRemoveActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        File file = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (file == null) {
            return;
        }

        tfPoster.setText(file.getAbsolutePath());
        setIcon(lbIcon, file);
    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage("Not selected movie", "Please select movie to update");
            return;
        }

        if (!formValid()) {
            return;
        }

        try {
            updateSelectedMovie(selectedMovie);
            updateMovieDirectorRelations();
            updateMovieActorRelations();

            movieTableModel.setMovies(movieRepo.selectAll());
            clearForm();
        } catch (IOException ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedMovie == null) {
            MessageUtils.showInformationMessage("Movie not selected", "Please select movie");
            return;
        }

        if (MessageUtils.showConfirmDialog("Delete movie", "Are you sure you want to delete the movie?")) {

            try {
                int movieId = selectedMovie.getId();

                List<MovieDirector> movieDirectors = movieDirectorRepo.selectMultiple(movieId);
                deleteMovieDirectors(movieDirectors);

                List<MovieActor> movieActors = movieActorRepo.selectMultiple(movieId);
                deleteMovieActors(movieActors);

                movieRepo.delete(movieId);

                if (selectedMovie.getPoster() != null) {
                    Files.deleteIfExists(Paths.get(selectedMovie.getPoster()));
                }

                movieTableModel.setMovies(movieRepo.selectAll());
                clearForm();
            } catch (IOException ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveAllMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAllMoviesActionPerformed
        try {
            MovieArchive movieArchive = loadMovies();
            JAXBUtils.save(movieArchive, FILENAME);
            MessageUtils.showInformationMessage("Info", "Movies successfully saved");
        } catch (Exception ex) {
            MessageUtils.showInformationMessage("Info", "Unable to save movies");
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveAllMoviesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActorRemove;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDirectorRemove;
    private javax.swing.JButton btnSaveAllMovies;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbDescriptionError;
    private javax.swing.JLabel lbGenreError;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbLinkError;
    private javax.swing.JLabel lbOriginalTitleError;
    private javax.swing.JLabel lbPicturePathError;
    private javax.swing.JLabel lbPubDateError;
    private javax.swing.JLabel lbReservationError;
    private javax.swing.JLabel lbTitleError;
    private javax.swing.JLabel lbTrailer;
    private javax.swing.JLabel lbTrailerError;
    private javax.swing.JLabel lbYearOfReleaseError;
    private javax.swing.JList<Actor> lsActors;
    private javax.swing.JList<Actor> lsAllActors;
    private javax.swing.JList<Director> lsAllDirectors;
    private javax.swing.JList<Director> lsDirectors;
    private javax.swing.JSpinner spDuration;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTable tblMovies;
    private javax.swing.JTextField tfGenre;
    private javax.swing.JTextField tfLink;
    private javax.swing.JTextField tfOriginalTitle;
    private javax.swing.JTextField tfPoster;
    private javax.swing.JTextField tfPubDate;
    private javax.swing.JTextField tfReservation;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfTrailer;
    private javax.swing.JTextField tfYearOfRelease;
    // End of variables declaration//GEN-END:variables

    private void init() {
        try {
            initValidation();
            hideErrors();
            initRepository();
            initTable();
            initDragAndDrop();
            loadListsForAllDDirectorsAndActors();
        } catch (Exception ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initValidation() {
        validationFields = Arrays.asList(tfTitle, tfPubDate, taDescription, tfPoster, tfYearOfRelease, tfGenre, tfOriginalTitle,
                tfLink, tfReservation, tfTrailer
        );

        errorLabels = Arrays.asList(
                lbTitleError, lbPubDateError, lbDescriptionError, lbPicturePathError, lbYearOfReleaseError, lbGenreError,
                lbOriginalTitleError, lbLinkError, lbReservationError, lbTrailerError
        );
    }

    private void hideErrors() {
        errorLabels.forEach(e -> e.setVisible(false));
    }

    private void initRepository() throws Exception {
        movieRepo = RepositoryFactory.getRepository(RepoType.MOVIE);
        directorRepo = RepositoryFactory.getRepository(RepoType.DIRECTOR);
        actorRepo = RepositoryFactory.getRepository(RepoType.ACTOR);
        movieDirectorRepo = RepositoryFactory.getRepository(RepoType.MOVIE_DIRECTOR);
        movieActorRepo = RepositoryFactory.getRepository(RepoType.MOVIE_ACTOR);
    }

    private void initTable() throws Exception {
        tblMovies.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblMovies.setAutoCreateRowSorter(true);
        tblMovies.setRowHeight(25);

        movieTableModel = new MovieTableModel(movieRepo.selectAll());
        tblMovies.setModel(movieTableModel);
    }

    private boolean formValid() {
        hideErrors();

        boolean ok = true;

        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setVisible(validationFields.get(i).getText().trim().isEmpty());
            if ("PubDate".equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(validationFields.get(i).getText().trim(), Movie.DATE_TIME_FORMATTER);
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }

            if ("YearOfRelease".equals(validationFields.get(i).getName())) {
                try {
                    Integer.parseInt(validationFields.get(i).getText().trim());
                } catch (NumberFormatException numberFormatException) {
                    ok = false;
                    errorLabels.get(i).setVisible(true);
                }
            }
        }

        return ok;
    }

    private void clearForm() throws Exception {
        hideErrors();
        validationFields.forEach(f -> f.setText(""));
        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/no_image.jpeg")));
        selectedMovie = null;
        clearLists();
    }
    
    private void clearLists(){
        directorsModel.clear();
        lsDirectors.setModel(directorsModel);
        
        actorsModel.clear();
        lsActors.setModel(actorsModel);
    }

    private String uploadPicture() throws IOException {
        String picturePath = tfPoster.getText();
        String ext = picturePath.substring(picturePath.lastIndexOf("."));
        String pictureName = UUID.randomUUID() + ext;
        String localPicturePath = DIR + File.separator + pictureName;

        FileUtils.copy(picturePath, localPicturePath);

        return localPicturePath;
    }

    private void setIcon(JLabel label, File file) {
        try {
            label.setIcon(IconUtils.createIcon(file, label.getWidth(), label.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadListsForAllDDirectorsAndActors() throws Exception {
        List<Director> allDirectors = directorRepo.selectAll();
        List<Actor> allActors = actorRepo.selectAll();

        allDirectorsModel.clear();
        allDirectors.forEach(allDirectorsModel::addElement);
        lsAllDirectors.setModel(allDirectorsModel);

        allActorsModel.clear();
        allActors.forEach(allActorsModel::addElement);
        lsAllActors.setModel(allActorsModel);
    }

    private void showMovie() throws Exception {
        clearForm();

        int selectedRow = tblMovies.getSelectedRow();
        int rowIndex = tblMovies.convertRowIndexToModel(selectedRow);
        int selectedMovieId = (int) movieTableModel.getValueAt(rowIndex, 0);

        try {
            Optional<Movie> optMovie = movieRepo.selectSingle(selectedMovieId);
            if (optMovie.isPresent()) {
                selectedMovie = optMovie.get();
                List<Director> directors = getDirectors(selectedMovie);
                List<Actor> actors = getActors(selectedMovie);

                directorsSet = new TreeSet<>(directors);
                actorsSet = new TreeSet<>(actors);

                selectedMovie.setDirectors(directors);
                selectedMovie.setActors(actors);

                fillForm(selectedMovie);
            }
        } catch (Exception ex) {
            Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillForm(Movie movie) {
        if (movie.getPoster() != null && Files.exists(Paths.get(movie.getPoster()))) {
            tfPoster.setText(movie.getPoster());
            setIcon(lbIcon, new File(movie.getPoster()));
        }

        tfTitle.setText(movie.getTitle());
        tfPubDate.setText(movie.getPublishedDate().format(Movie.DATE_TIME_FORMATTER));
        taDescription.setText(movie.getDescription());
        spDuration.setValue(movie.getDuration());
        tfYearOfRelease.setText(((Integer) movie.getYearOfRelease()).toString());
        tfGenre.setText(movie.getGenre());
        tfOriginalTitle.setText(movie.getOriginalTitle());
        tfLink.setText(movie.getLink());
        tfReservation.setText(movie.getReservation());
        tfTrailer.setText(movie.getTrailer());

        loadDirectorsModel();
        loadActorsModel();
    }

    private List<Director> getDirectors(Movie selectedMovie) throws Exception {
        List<Director> directors = new ArrayList<>();

        int movieId = selectedMovie.getId();
        List<MovieDirector> movieDirectors = movieDirectorRepo.selectMultiple(movieId);
        List<Integer> directorIds = movieDirectors.stream()
                .map(d -> d.getDirectorId())
                .collect(Collectors.toList());

        directorIds.forEach(id -> {
            try {
                directors.add(directorRepo.selectSingle(id).get());
            } catch (Exception ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        return directors;
    }

    private List<Actor> getActors(Movie selectedMovie) throws Exception {
        List<Actor> actors = new ArrayList<>();

        int movieId = selectedMovie.getId();
        List<MovieActor> movieActors = movieActorRepo.selectMultiple(movieId);
        List<Integer> actorIds = movieActors.stream()
                .map(a -> a.getActorId())
                .collect(Collectors.toList());

        actorIds.forEach(id -> {
            try {
                actors.add(actorRepo.selectSingle(id).get());
            } catch (Exception ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

        return actors;
    }

    private void loadDirectorsModel() {
        directorsModel.clear();
        directorsSet.forEach(directorsModel::addElement);
        lsDirectors.setModel(directorsModel);
    }

    private void loadActorsModel() {
        actorsModel.clear();
        actorsSet.forEach(actorsModel::addElement);
        lsActors.setModel(actorsModel);
    }

    private void initDragAndDrop() {
        lsAllDirectors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsAllDirectors.setDragEnabled(true);
        lsAllDirectors.setTransferHandler(new DirectorExportTransferHandler());

        lsDirectors.setDropMode(DropMode.ON);
        lsDirectors.setTransferHandler(new DirectorImportTransferHandler());

        lsAllActors.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsAllActors.setDragEnabled(true);
        lsAllActors.setTransferHandler(new ActorExportTransferHandler());

        lsActors.setDropMode(DropMode.ON);
        lsActors.setTransferHandler(new ActorImportTransferHandler());
    }

    private void addMovieDirectors(int movieId) throws Exception {
        List<MovieDirector> movieDirectors = new ArrayList<>();

        for (Director director : directorsSet) {
            movieDirectors.add(new MovieDirector(movieId, director.getId()));
        }

        movieDirectorRepo.createMultiple(movieDirectors);
    }

    private void addMovieActors(int movieId) throws Exception {
        List<MovieActor> movieActors = new ArrayList<>();

        for (Actor actor : actorsSet) {
            movieActors.add(new MovieActor(movieId, actor.getId()));
        }

        movieActorRepo.createMultiple(movieActors);
    }

    private void updateSelectedMovie(Movie selectedMovie) throws IOException, Exception {
        if (!tfPoster.getText().trim().equals(selectedMovie.getPoster())) {
            if (selectedMovie.getPoster() != null) {
                Files.deleteIfExists(Paths.get(selectedMovie.getPoster()));
            }

            String localPicturePath = uploadPicture();
            selectedMovie.setPoster(localPicturePath);
        }

        selectedMovie.setTitle(tfTitle.getText().trim());
        selectedMovie.setPublishedDate(LocalDateTime.parse(tfPubDate.getText().trim(), Movie.DATE_TIME_FORMATTER));
        selectedMovie.setDescription(taDescription.getText().trim());
        selectedMovie.setOriginalTitle(tfOriginalTitle.getText().trim());
        selectedMovie.setDuration((int) spDuration.getValue());
        selectedMovie.setYearOfRelease(Integer.parseInt(tfYearOfRelease.getText().trim()));
        selectedMovie.setGenre(tfGenre.getText().trim());
        selectedMovie.setLink(tfLink.getText().trim());
        selectedMovie.setReservation(tfReservation.getText().trim());
        selectedMovie.setTrailer(tfTrailer.getText().trim());

        movieRepo.update(selectedMovie.getId(), selectedMovie);
    }

    private void updateMovieDirectorRelations() throws Exception {
        List<MovieDirector> movieDirectors = movieDirectorRepo.selectMultiple(selectedMovie.getId());

        List<Integer> directorIdsFromDb = movieDirectors
                .stream()
                .map(md -> md.getDirectorId())
                .collect(Collectors.toList());

        List<Integer> directorIdsFromList = directorsSet
                .stream()
                .map(d -> d.getId())
                .collect(Collectors.toList());

        deleteOldMovieDirectorRelations(movieDirectors, directorIdsFromDb, directorIdsFromList);
        createNewMovieDirectorRelations(movieDirectors, directorIdsFromDb, directorIdsFromList);
    }

    private void deleteOldMovieDirectorRelations(List<MovieDirector> movieDirectors, List<Integer> directorIdsFromDb, List<Integer> directorIdsFromList) throws Exception, Exception {
        List<Integer> directorIdsFromDbCopy = new ArrayList<>(directorIdsFromDb);
        directorIdsFromDbCopy.removeAll(directorIdsFromList);

        if (!directorIdsFromDbCopy.isEmpty()) {
            for (MovieDirector movieDirector : movieDirectors) {
                if (directorIdsFromDbCopy.contains(movieDirector.getDirectorId())) {
                    movieDirectorRepo.delete(movieDirector.getId());
                }
            }
        }
    }

    private void createNewMovieDirectorRelations(List<MovieDirector> movieDirectors, List<Integer> directorIdsFromDb, List<Integer> directorIdsFromList) throws Exception {
        List<Integer> directorsIdsFromListCopy = new ArrayList<>(directorIdsFromList);
        directorsIdsFromListCopy.removeAll(directorIdsFromDb);

        if (!directorsIdsFromListCopy.isEmpty()) {
            for (Integer directorId : directorsIdsFromListCopy) {
                movieDirectorRepo.createSingle(new MovieDirector(selectedMovie.getId(), directorId));
            }
        }
    }

    private void updateMovieActorRelations() throws Exception {
        List<MovieActor> movieActors = movieActorRepo.selectMultiple(selectedMovie.getId());

        List<Integer> actorIdsFromDb = movieActors
                .stream()
                .map(ma -> ma.getActorId())
                .collect(Collectors.toList());

        List<Integer> actorIdsFromList = actorsSet
                .stream()
                .map(a -> a.getId())
                .collect(Collectors.toList());

        deleteOldMovieActorRelations(movieActors, actorIdsFromDb, actorIdsFromList);
        createNewMovieActorRelations(movieActors, actorIdsFromDb, actorIdsFromList);
    }

    private void deleteOldMovieActorRelations(List<MovieActor> movieActors, List<Integer> actorIdsFromDb, List<Integer> actorIdsFromList) throws Exception {
        List<Integer> actorIdsFromDbCopy = new ArrayList<>(actorIdsFromDb);
        actorIdsFromDbCopy.removeAll(actorIdsFromList);

        if (!actorIdsFromDbCopy.isEmpty()) {
            for (MovieActor movieActor : movieActors) {
                if (actorIdsFromDbCopy.contains(movieActor.getActorId())) {
                    movieActorRepo.delete(movieActor.getId());
                }
            }
        }
    }

    private void createNewMovieActorRelations(List<MovieActor> movieActors, List<Integer> actorIdsFromDb, List<Integer> actorIdsFromList) throws Exception {
        List<Integer> actorsIdsFromListCopy = new ArrayList<>(actorIdsFromList);
        actorsIdsFromListCopy.removeAll(actorIdsFromDb);

        if (!actorsIdsFromListCopy.isEmpty()) {
            for (Integer actorId : actorsIdsFromListCopy) {
                movieActorRepo.createSingle(new MovieActor(selectedMovie.getId(), actorId));
            }
        }
    }

    private void deleteMovieDirectors(List<MovieDirector> movieDirectors) throws Exception {
        for (MovieDirector movieDirector : movieDirectors) {
            movieDirectorRepo.delete(movieDirector.getId());
        }
    }

    private void deleteMovieActors(List<MovieActor> movieActors) throws Exception {
        for (MovieActor movieActor : movieActors) {
            movieActorRepo.delete(movieActor.getId());
        }
    }

    private MovieArchive loadMovies() throws Exception {
        List<Movie> allMovies = movieRepo.selectAll();
        List<Director> allDirectors = directorRepo.selectAll();
        List<Actor> allActors = actorRepo.selectAll();
        
        for (Movie movie : allMovies) {
            List<MovieDirector> movieDirectors = movieDirectorRepo.selectMultiple(movie.getId());
            List<Director> directors = new ArrayList<>();
            for (MovieDirector movieDirector : movieDirectors) {
                Optional<Director> optDirector = directorRepo.selectSingle(movieDirector.getDirectorId());
                if(optDirector.isPresent()){
                    directors.add(optDirector.get());
                }
            }
            
            movie.setDirectors(directors);
        }
        
        for (Movie movie : allMovies) {
            List<MovieActor> movieActors = movieActorRepo.selectMultiple(movie.getId());
            List<Actor> actors = new ArrayList<>();
            for (MovieActor movieActor : movieActors) {
                Optional<Actor> optActor = actorRepo.selectSingle(movieActor.getActorId());
                if(optActor.isPresent()){
                    actors.add(optActor.get());
                }
            }
            
            movie.setActors(actors);
        }
        
        return new MovieArchive(allMovies);
    }

    private class DirectorExportTransferHandler extends TransferHandler {

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;
        }

        @Override
        protected Transferable createTransferable(JComponent c) {
            return new DirectorTransferable(lsAllDirectors.getSelectedValue());
        }
    }

    private class DirectorImportTransferHandler extends TransferHandler {

        @Override
        public boolean canImport(TransferSupport support) {
            return support.isDataFlavorSupported(DirectorTransferable.DIRECTOR_FLAVOR);
        }

        @Override
        public boolean importData(TransferSupport support) {
            Transferable transferable = support.getTransferable();

            try {
                Director director = (Director) transferable.getTransferData(DirectorTransferable.DIRECTOR_FLAVOR);

                if (directorsSet.add(director)) {
                    loadDirectorsModel();
                    return true;
                }
            } catch (UnsupportedFlavorException | IOException ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            }

            return false;
        }
    }

    private class ActorExportTransferHandler extends TransferHandler {

        @Override
        public int getSourceActions(JComponent c) {
            return COPY;
        }

        @Override
        protected Transferable createTransferable(JComponent c) {
            return new ActorTransferable(lsAllActors.getSelectedValue());
        }

    }

    private class ActorImportTransferHandler extends TransferHandler {

        @Override
        public boolean canImport(TransferSupport support) {
            return support.isDataFlavorSupported(ActorTransferable.ACTOR_FLAVOR);
        }

        @Override
        public boolean importData(TransferSupport support) {
            Transferable transferable = support.getTransferable();

            try {
                Actor actor = (Actor) transferable.getTransferData(ActorTransferable.ACTOR_FLAVOR);

                if (actorsSet.add(actor)) {
                    loadActorsModel();
                    return true;
                }
            } catch (UnsupportedFlavorException | IOException ex) {
                Logger.getLogger(Movies.class.getName()).log(Level.SEVERE, null, ex);
            }

            return false;
        }
    }
}
